# Generated by Django 4.1.7 on 2023-04-10 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bamazon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='rating',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='bamazon.rating'),
            preserve_default=False,
        ),
    ]
